Set FontSize 16
Set Width 1200
Set Height 700
Set Margin 20
Set MarginFill "#aaaaaa"
Set BorderRadius 10
Set WindowBar Colorful
Set TypingSpeed 75ms

Type "colorstorm -m"
Sleep 500ms
Enter
Sleep 1s

Type "My Mono Color Theme"
Sleep 1s
Tab
Sleep 500ms
Enter
Sleep 1s
Tab
Sleep 125ms
Down
Sleep 125ms
Down
Sleep 125ms
Down
Sleep 125ms
Down
Sleep 125ms
Down
Sleep 125ms
Left
Left
Left
Left
Left
Left
Left
Left
Left
Left
Left
Left
Tab
Sleep 500ms
Enter
Sleep 2s
