name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1.5"
    - name: Install dependencies
      run: sudo apt-get install -y jq libxml2-utils vim php npm nodejs
    - name: Build theme files
      run: |
          npm install less
          git submodule init
          git submodule update
          lua build.lua all
          
          # Vim themes need extra work for cterm colors
          cd vim
          git submodule init
          git submodule update
          ./build.sh
          cd ..
    - name: Validate theme files
      run: ./validate.sh
