name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install build-essential jq
    - name: Build theme files
      run: |
          git submodule init
          git submodule update
          make clean
          make
          ./earthbound-themes
    - name: Validate theme files
      run: for file in vscode/themes/*.json; do cat $file | jq .; done
