name: release

on:
  create:
jobs:
  build-releases:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: |
          ${{ secrets.ATOM_SUBMODULE_KEY }}
          ${{ secrets.VSCODE_SUBMODULE_KEY }}
          ${{ secrets.VIM_SUBMODULE_KEY }}
          ${{ secrets.SUBLIME_SUBMODULE_KEY }}
          ${{ secrets.PRIMARY_REPO_KEY }}
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1.5"
    - uses: UziTech/action-setup-atom@v2
      with:
        version: 'stable'
    - name: Install dependencies
      run: sudo apt-get install npm nodejs php
    - name: Build theme files
      run: |
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

          npm install -g vsce
          git submodule init
          git submodule update
          TAG_NAME="${GITHUB_REF#refs/tags/v}"
          lua build.lua all
          
          echo "Building release for version $TAG_NAME"
          
          # VSCode
          echo "============= VSCODE ============="
          cd vscode
          git remote set-url origin git@github.com:benbusby/vscode-earthbound-themes.git
          git checkout main
          git add .
          git commit --allow-empty -m "[AUTO] Version $TAG_NAME release"
          git tag -a -m "Version $TAG_NAME tag" v"$TAG_NAME"
          git push --follow-tags
          vsce publish "$TAG_NAME" -p "$VSCODE_TOKEN"
          git remote set-url origin https://github.com/benbusby/vscode-earthbound-themes.git
          cd ..
          
          # Sublime
          echo "============= SUBLIME ============="
          cd sublime
          git remote set-url origin git@github.com:benbusby/sublime-earthbound-themes.git
          git checkout main
          git add .
          git commit --allow-empty -m "[AUTO] Version $TAG_NAME release"
          git tag -a -m "Version $TAG_NAME tag" v"$TAG_NAME"
          git push --follow-tags
          git remote set-url origin https://github.com/benbusby/sublime-earthbound-themes.git
          cd ..
          
          # Vim
          echo "============= VIM ============="
          cd vim
          git remote set-url origin git@github.com:benbusby/vim-earthbound-themes.git
          git submodule init
          git submodule update
          ./build.sh
          git checkout main
          git add .
          git commit --allow-empty -m "[AUTO] Version $TAG_NAME release"
          git tag -a -m "Version $TAG_NAME tag" v"$TAG_NAME"
          git push --follow-tags
          git remote set-url origin https://github.com/benbusby/vim-earthbound-themes.git
          cd ..
          tar -czvf vim-earthbound-themes.tar.gz -C vim/colors .
          
          # Atom
          echo "============= ATOM ============="
          cd atom
          git remote set-url origin git@github.com:benbusby/atom-earthbound-themes.git
          git checkout master
          TMP_PACKAGE=$(mktemp)
          jq --arg tag "$TAG_NAME" '.version = $tag' package.json > "$TMP_PACKAGE" && mv "$TMP_PACKAGE" package.json
          git add .
          git commit --allow-empty -m "[AUTO] Version $TAG_NAME release"
          git tag -a -m "Version $TAG_NAME tag" v"$TAG_NAME"
          git push --follow-tags
          apm publish --tag v"$TAG_NAME"
          git remote set-url origin https://github.com/benbusby/atom-earthbound-themes.git
          cd ..
          
          # Update main repo submodules
          echo "============= FINISHING UP ============="
          git remote set-url origin git@github.com:benbusby/earthbound-themes.git
          git checkout main
          git add vscode vim atom sublime
          git commit --allow-empty -m "[AUTO] Version $TAG_NAME submodule update"
          git push
          
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: vim-earthbound-themes.tar.gz
