name: update

on:
  push:
    branches: [ main ]

jobs:
  build-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Verify themes changed
      uses: tj-actions/verify-changed-files@v8.6
      id: verify-changed-files
      with:
        files: |
          build.lua
          templates

    - uses: webfactory/ssh-agent@v0.5.3
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      with:
        ssh-private-key: |
          ${{ secrets.ATOM_SUBMODULE_KEY }}
          ${{ secrets.VSCODE_SUBMODULE_KEY }}
          ${{ secrets.VIM_SUBMODULE_KEY }}
          ${{ secrets.SUBLIME_SUBMODULE_KEY }}
          ${{ secrets.PRIMARY_REPO_KEY }}

    - uses: leafo/gh-actions-lua@v8.0.0
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      with:
        luaVersion: "5.1.5"

    - name: Install dependencies
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: sudo apt-get install npm nodejs php

    - name: Build theme files
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

          git submodule init
          git submodule update
          lua build.lua all

          export EB_REPO="https://github.com/benbusby/earthbound-themes/commit"
          
          echo "Building release for version $TAG_NAME"
          
          # VSCode
          echo "============= VSCODE ============="
          cd vscode
          git remote set-url origin git@github.com:benbusby/vscode-earthbound-themes.git
          git checkout main
          git add .
          git commit --allow-empty -m "[CI] Automatic update" -m "$EB_REPO/$GITHUB_SHA"
          git push 
          cd ..
          
          # Sublime
          echo "============= SUBLIME ============="
          cd sublime
          git remote set-url origin git@github.com:benbusby/sublime-earthbound-themes.git
          git checkout main
          git add .
          git commit --allow-empty -m "[CI] Automatic update" -m "$EB_REPO/$GITHUB_SHA"
          git push
          cd ..
          
          # Vim
          echo "============= VIM ============="
          cd vim
          git remote set-url origin git@github.com:benbusby/vim-earthbound-themes.git
          git submodule init
          git submodule update
          ./build.sh
          git checkout main
          git add .
          git commit --allow-empty -m "[CI] Automatic update" -m "$EB_REPO/$GITHUB_SHA"
          git push
          cd ..
          
          # Atom
          echo "============= ATOM ============="
          cd atom
          git remote set-url origin git@github.com:benbusby/atom-earthbound-themes.git
          git checkout master
          git add .
          git commit --allow-empty -m "[CI] Automatic update" -m "$EB_REPO/$GITHUB_SHA"
          git push
          cd ..
          
          # Update main repo submodules
          echo "============= FINISHING UP ============="
          git remote set-url origin git@github.com:benbusby/earthbound-themes.git
          git checkout main
          git add vscode vim atom sublime
          git commit --allow-empty -m "[CI] Auto submodule update"
          git push
